---
title: "p8105_hw3_sdc2157"
author: "Stephanie Calluori"
date: 2023-10-14
output: github_document
---

```{r, data import, results = FALSE, message = FALSE}
library(tidyverse)
library(p8105.datasets)

data("instacart")

data("brfss_smart2010")

demographic_raw <- read_csv("data/nhanes_covar.csv", skip = 4, col_names = TRUE)
head(demographic_raw)
tail(demographic_raw)
colnames(demographic_raw)

accel_raw <- read_csv("data/nhanes_accel.csv", col_names = TRUE)
head(accel_raw)
tail(accel_raw)
colnames(accel_raw)
```

```{r, setup, echo = FALSE, results = FALSE, message = FALSE}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


# Problem 1

```{r}
instacart_clean <- instacart |> 
  janitor::clean_names()

head(instacart_clean)

str(instacart_clean)

sum(is.na(instacart_clean))

num_users <- instacart_clean |> 
  distinct(user_id)

```


The data set describes

The data set contains `r nrow(instacart_clean)` observations and `r ncol(instacart_clean)`. Each observation corresponds to a distinct instacart product. Variables include `r colnames(instacart_clean)`.

```{r}
num_aisle <- instacart_clean |> 
  count(aisle_id) |> 
  nrow()

aisle_items <- instacart_clean |> 
  select(aisle, product_name) |> 
  group_by(aisle) |> 
  summarize(
    n_items = n()
  ) |> 
  arrange(desc(n_items))

```

fresh veggies, fresh fruits, and packaged vegtables/fruits
